stages:
  - build
  - test
  - sonarqube

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Diretório onde o scanner será instalado

sonarqube-check:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner
      -Dsonar.projectKey=jno868214_agendaapp-backend
      -Dsonar.organization=Jeferson Araujo 
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.login=backend
  allow_failure: true
  only:
    - branches
    - main
