stages:
  - build
  - test
  - scan

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

cache:
  paths:
    - .sonar/cache

before_script:
  - choco install openjdk11 --params 'installdir=c:\\java\\openjdk11' -y # Instala o OpenJDK 11 usando Chocolatey
  - SET "JAVA_HOME=c:\java\openjdk11" # Define o JAVA_HOME para o OpenJDK 11
  - SET "PATH=%JAVA_HOME%\bin;%PATH%" # Adiciona o OpenJDK 11 ao PATH
  - dotnet tool install --global dotnet-sonarscanner

build:
  stage: build
  script:
    - dotnet build --configuration Release

test:
  stage: test
  script:
    - dotnet test --configuration Release --no-build

sonarqube-check:
  stage: scan
  script:
    - dotnet sonarscanner begin /k:"jno868214_agendaapp-backend" /o:"jno868214" /d:sonar.login="${SONAR_TOKEN}" /d:sonar.host.url="https://sonarcloud.io"
    - dotnet build --configuration Release
    - dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
